[workspace]
members = ["contracts"]

[workspace.package]
edition = "2024_07"
version = "0.1.0"

[workspace.dependencies]
assert_macros = "2.12.3"
openzeppelin = "2.0.0"
openzeppelin_testing = "3.0.0"
snforge_std = "0.54.1"
starknet = "2.12.2"
starkware_utils = {git = "https://github.com/starkware-libs/starkware-starknet-utils", rev = "9aa2ec0b1dc1bc54bc01705cb2d4f5227e28e1e7"}
starkware_utils_testing = {git = "https://github.com/starkware-libs/starkware-starknet-utils", rev = "9aa2ec0b1dc1bc54bc01705cb2d4f5227e28e1e7"}

[workspace.tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[workspace.tool.fmt]
sort-module-level-items = true

[profile.dev.cairo]
inlining-strategy = "avoid"
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true
