[package]
edition.workspace = true
name = "contracts"
version.workspace = true

[dependencies]
openzeppelin.workspace = true
starknet.workspace = true
starkware_utils.workspace = true

[dev-dependencies]
assert_macros.workspace = true
snforge_std.workspace = true
starkware_utils_testing.workspace = true

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"

[lib]

[profile.dev.cairo]
inlining-strategy = "avoid"
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true

[[test]]
build-external-contracts = ["starkware_utils::erc20::erc20_mocks::DualCaseERC20Mock"]
name = "contracts_unittest"
